from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .io import norm, read_jsonl, sha_text


REQUIRED = {
    "response_id",
    "canonical_id",
    "q",
    "y",
    "target_provider",
    "requested_target_model",
    "resolved_target_model",
}


def load_v10_registry(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    rows = []
    rejects = Counter()
    seen = {}
    conflicts = []
    for raw in read_jsonl(path):
        missing = [k for k in REQUIRED if raw.get(k) in {None, ""}]
        if missing:
            rejects["missing_required"] += 1
            continue
        if raw.get("status") not in {"ok", "success", None, ""}:
            rejects["bad_status"] += 1
            continue
        q = raw["q"]
        y = raw["y"]
        if len(norm(q)) < 20 or len(norm(y)) < 10:
            rejects["too_short"] += 1
            continue
        key = (
            sha_text(norm(q)),
            sha_text(norm(y)),
            raw.get("resolved_target_model") or raw.get("requested_target_model"),
            raw.get("request_id", ""),
        )
        if key in seen and seen[key] != raw["response_id"]:
            conflicts.append({"key": key, "left": seen[key], "right": raw["response_id"]})
            rejects["dedupe"] += 1
            continue
        seen[key] = raw["response_id"]
        rows.append(canonicalize_v10(raw, key))
    audit = {
        "source_file": str(path),
        "accepted": len(rows),
        "rejects": dict(rejects),
        "conflicts": conflicts[:20],
        "conflict_count": len(conflicts),
        "by_target_provider": dict(Counter(r["target_provider"] for r in rows)),
        "by_language": dict(Counter(r["language"] for r in rows)),
        "by_category": dict(Counter(r["fraud_category"] for r in rows)),
        "target_model_mismatch": 0,
        "duplicate_conflicts": len(conflicts),
    }
    return rows, audit


def canonicalize_v10(raw: dict[str, Any], key: tuple[str, str, str, str]) -> dict[str, Any]:
    return {
        "target_response_id": raw["response_id"],
        "canonical_case_id": raw.get("canonical_id") or raw.get("canonical_q_id") or raw["response_id"],
        "exact_q_hash": raw.get("exact_q_sha256") or key[0],
        "normalized_q_hash": raw.get("normalized_q_sha256") or key[0],
        "semantic_q_component": raw.get("canonical_id") or raw.get("semantic_cluster_id") or raw["response_id"],
        "y_hash": raw.get("normalized_y_sha256") or key[1],
        "source_dataset": "Fraud-R1/V10-natural",
        "source_file": raw.get("source_run", "E1_V10_RESPONSE_REGISTRY"),
        "source_schema": raw.get("registry_version", "e1_v10_registry_v1"),
        "source_license": "Fraud-R1 research dataset; target responses generated by local API run",
        "source_split": raw.get("exclusion_reason", ""),
        "target_provider": raw["target_provider"],
        "requested_target_model": raw["requested_target_model"],
        "resolved_target_model": raw["resolved_target_model"],
        "generation_request_id": raw.get("request_id", ""),
        "generation_parameters": {
            "temperature": raw.get("generation_temperature", ""),
            "top_p": raw.get("generation_top_p", ""),
            "max_tokens": raw.get("generation_max_tokens", ""),
        },
        "is_real_target_response": True,
        "is_open_source_response": False,
        "prior_label_schema": raw.get("label_schema_versions", ""),
        "prior_use_scope": "E1-A/E1-C natural registry",
        "q_private": raw["q"],
        "y_private": raw["y"],
        "language": raw.get("language", "unknown"),
        "fraud_category": normalize_category(raw.get("category", "")),
        "old_gold": int(raw.get("material_assist_consensus") or 0),
    }


def normalize_category(value: str) -> str:
    text = (value or "").lower()
    if "job" in text:
        return "fake_job"
    if "phish" in text:
        return "phishing"
    if "imperson" in text:
        return "impersonation"
    if "service" in text:
        return "fraudulent_service"
    if "relationship" in text or "dating" in text or "romance" in text:
        return "relationship_investment"
    return text.replace(" ", "_") or "unknown"
