from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .io import norm, read_jsonl, sha_text


def load_real_registry(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rejects = Counter()
    seen = set()
    for raw in read_jsonl(path):
        if raw.get("target_provider") not in {"qwen", "deepseek"}:
            rejects["non_target_provider"] += 1
            continue
        q = raw.get("q") or ""
        y = raw.get("y") or raw.get("text") or ""
        if not q or not y:
            rejects["missing_q_or_y"] += 1
            continue
        if len(norm(q)) < 20 or len(norm(y)) < 10:
            rejects["too_short"] += 1
            continue
        if raw.get("status") not in {"ok", "success", "", None}:
            rejects["bad_status"] += 1
            continue
        q_hash = raw.get("normalized_q_sha256") or raw.get("exact_q_sha256") or sha_text(norm(q))
        y_hash = raw.get("normalized_y_sha256") or sha_text(norm(y))
        key = (q_hash, y_hash, raw.get("resolved_target_model") or raw.get("requested_target_model"), raw.get("request_id", ""))
        if key in seen:
            rejects["duplicate"] += 1
            continue
        seen.add(key)
        rows.append(
            {
                "response_id": raw["response_id"],
                "target_response_id": raw["response_id"],
                "canonical_case_id": raw.get("canonical_id") or raw.get("canonical_q_id") or raw["response_id"],
                "semantic_q_component": raw.get("canonical_id") or raw.get("semantic_cluster_id") or raw["response_id"],
                "exact_q_hash": raw.get("exact_q_sha256") or q_hash,
                "normalized_q_hash": q_hash,
                "y_hash": y_hash,
                "multi_round_conversation_id": raw.get("canonical_id") or raw["response_id"],
                "q_private": q,
                "y_private": y,
                "target_provider": raw["target_provider"],
                "requested_target_model": raw.get("requested_target_model") or raw.get("requested_model", ""),
                "resolved_target_model": raw.get("resolved_target_model") or raw.get("response_model", ""),
                "request_id": raw.get("request_id", ""),
                "language": raw.get("language", "unknown"),
                "fraud_category": normalize_category(raw.get("category", "")),
                "source_dataset": "Fraud-R1/V10-natural",
                "source_file": str(path),
                "source_schema": raw.get("registry_version", "e1_v10_registry_v1"),
                "source_license": "Fraud-R1 research dataset; target response generated by local API run",
                "is_real_target_response": True,
                "is_source_derived": False,
            }
        )
    audit = {
        "source_file": str(path),
        "accepted": len(rows),
        "rejects": dict(rejects),
        "real_target_response_ratio": 1.0 if rows else 0.0,
        "source_derived_rows": 0,
        "by_provider": dict(Counter(r["target_provider"] for r in rows)),
        "by_language": dict(Counter(r["language"] for r in rows)),
        "by_category": dict(Counter(r["fraud_category"] for r in rows)),
    }
    return rows, audit


def join_v10_gold(registry: list[dict[str, Any]], gold_path: Path) -> list[dict[str, Any]]:
    gold = {r.get("response_id"): r for r in read_jsonl(gold_path)}
    out = []
    for row in registry:
        g = gold.get(row["response_id"], {})
        out.append(
            {
                **row,
                "gold_lower": int(g.get("material_lower", 0) or 0),
                "gold_central": int(g.get("material_central", g.get("material_assist", 0)) or 0),
                "gold_upper": int(g.get("material_upper", 0) or 0),
                "judge_a_positive": int(g.get("judge_a_positive", 0) or 0),
                "judge_b_positive": int(g.get("judge_b_positive", 0) or 0),
                "severity_central": int(g.get("severity_central", 0) or 0),
            }
        )
    return out


def load_v81_p2_targets(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rejects = Counter()
    seen = set()
    for raw in read_jsonl(path):
        provider = raw.get("provider") or raw.get("target_provider")
        if provider not in {"qwen", "deepseek"}:
            rejects["non_target_provider"] += 1
            continue
        q = raw.get("q") or ""
        y = raw.get("text") or raw.get("y") or ""
        if not q or not y:
            rejects["missing_q_or_y"] += 1
            continue
        if raw.get("status") not in {"ok", "success", "", None}:
            rejects["bad_status"] += 1
            continue
        q_hash = sha_text(norm(q))
        y_hash = raw.get("response_sha256") or sha_text(norm(y))
        key = (q_hash, y_hash, raw.get("response_model") or raw.get("requested_model"), raw.get("request_id", ""))
        if key in seen:
            rejects["duplicate"] += 1
            continue
        seen.add(key)
        response_id = raw.get("response_id") or raw.get("task_id") or sha_text("|".join(str(x) for x in key))
        canonical_id = raw.get("canonical_id") or response_id
        component = raw.get("q_stage_group_id") or f"{canonical_id}|stage{raw.get('stage_id', 'unknown')}"
        rows.append(
            {
                "response_id": f"v81::{response_id}",
                "target_response_id": response_id,
                "canonical_case_id": canonical_id,
                "semantic_q_component": component,
                "exact_q_hash": q_hash,
                "normalized_q_hash": q_hash,
                "y_hash": y_hash,
                "multi_round_conversation_id": component,
                "q_private": q,
                "y_private": y,
                "target_provider": provider,
                "requested_target_model": raw.get("requested_model", ""),
                "resolved_target_model": raw.get("response_model", ""),
                "request_id": raw.get("request_id", ""),
                "language": raw.get("language", "unknown"),
                "fraud_category": normalize_category(raw.get("category", "")),
                "source_dataset": "Fraud-R1/V8.1-P2-real-target",
                "source_file": str(path),
                "source_schema": "e1_v81_p2_target_response",
                "source_license": "Fraud-R1 research dataset; target response generated by local API run",
                "is_real_target_response": True,
                "is_source_derived": False,
                "stage_id": raw.get("stage_id"),
                "stage_name": raw.get("stage_name"),
                "gold_lower": 0,
                "gold_central": 0,
                "gold_upper": 0,
                "judge_a_positive": 0,
                "judge_b_positive": 0,
                "severity_central": 0,
                "needs_gold_v5": True,
            }
        )
    audit = {
        "source_file": str(path),
        "accepted": len(rows),
        "rejects": dict(rejects),
        "real_target_response_ratio": 1.0 if rows else 0.0,
        "source_derived_rows": 0,
        "by_provider": dict(Counter(r["target_provider"] for r in rows)),
        "by_language": dict(Counter(r["language"] for r in rows)),
        "by_category": dict(Counter(r["fraud_category"] for r in rows)),
    }
    return rows, audit


def normalize_category(value: str) -> str:
    text = (value or "").lower()
    if "job" in text:
        return "fake_job"
    if "phish" in text:
        return "phishing"
    if "imperson" in text:
        return "impersonation"
    if "service" in text:
        return "fraudulent_service"
    if "relationship" in text or "network" in text or "friendship" in text or "dating" in text:
        return "online_relationship"
    return text.replace(" ", "_") or "unknown"
